name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.12

- pip:
  # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
- scikit-learn=0.22
- scipy=1.3.2
- joblib=0.13.2
- numpy=1.19.2
- pandas=1.1.3
- matplotlib=3.3.2
- torch=1.00
- torchvision=0.2.2
- tqdm=4.40.2
